name: Rust

on:
  push:
    branches: [ dev, rococo ]
  pull_request:
    branches: [ dev, rococo ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add wasm toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target: wasm32-unknown-unknown
        override: true
    - name: Build
      run: cargo build
    - name: Run unit tests
      run: cargo test --verbose
# SBP M1 review: you could also run cargo clippy for some general code hygiene recommandations ...
