name: Remote Dispatch Action Initiator
 
on:
  push:
    branches: [ dev, rococo ]
 
jobs:
  pull-request-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch pull request trigger event
        run: |
          curl -X POST https://api.github.com/repos/litentry/litentry-node/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "integration-test-trigger", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'", "ref": "${{ github.ref }}", "sha": "${{ github.sha }}"  }}'
          curl -X POST https://api.github.com/repos/litentry/litentry-parachain/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "integration-test-trigger", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'", "ref": "${{ github.ref }}", "sha": "${{ github.sha }}" }}'
